### ISSUE TITLE
Incident report: create_dataset.py err when ran on Sockeye

### ISSUE THREAD

**Issue by lisatwyw** [BCCDC-DSI/RADD#26]
**python create_dataset.py**

```
   Compound Compound Name    Workflow Associated Target Peak MS Order Precursor m/z Product m/z        m/z Height Threshold  ... Target Ratio Window Type  PeakPolarity  Adduct  Charge State  Retention Time  Retention Time Window  Integration Strategy PTC Confirmed RT
0  Ketamine  (-)-Ketamine  TargetPeak                    NaN      ms1     238.09932   238.09932  238.09932             5000  ...          NaN   eAbsolute      Positive     M+H           1.0            3.77                   30.0            Individual             3.99
1  Ketamine  (-)-Ketamine    Fragment                      1      ms2     238.09932   125.01541  125.01541             5000  ...          NaN   eAbsolute      Positive     M+H           1.0            3.77                   30.0            Individual             3.99
2  Ketamine  (-)-Ketamine    Fragment                      1      ms2     238.09932   179.06221  179.06221             5000  ...          NaN   eAbsolute      Positive     M+H           1.0            3.77                   30.0            Individual             3.99
3  Ketamine  (-)-Ketamine    Fragment                      1      ms2     238.09932   207.05737  207.05737             5000  ...          NaN   eAbsolute      Positive     M+H           1.0            3.77                   30.0            Individual             3.99
4  Ketamine  (-)-Ketamine    Fragment                      1      ms2     238.09932   220.08827  220.08827             5000  ...          NaN   eAbsolute      Positive     M+H           1.0            3.77                   30.0            Individual             3.99

[5 rows x 25 columns]
Traceback (most recent call last):
  File "/arc/project/st-ashapi01-1/RADD/workflow2b/create_dataset.py", line 77, in <module>
    data = add_smiles_to_data(data, 'Compound Name')
  File "/arc/project/st-ashapi01-1/RADD/workflow2b/create_dataset.py", line 67, in add_smiles_to_data
    smiles_dict = {compound: compound_name_to_smiles(compound) for compound in unique_compounds}
  File "/arc/project/st-ashapi01-1/RADD/workflow2b/create_dataset.py", line 67, in <dictcomp>
    smiles_dict = {compound: compound_name_to_smiles(compound) for compound in unique_compounds}
  File "/arc/project/st-ashapi01-1/RADD/workflow2b/create_dataset.py", line 49, in compound_name_to_smiles
    raise ValueError("Input must be a string or a pandas Series.")
ValueError: Input must be a string or a pandas Series.
```

**Comment by lisatwyw** [comment]
not important anymore
